FROM nginx:alpine

# Rimuove la configurazione di default
RUN rm /etc/nginx/conf.d/default.conf

# Copia la configurazione personalizzata di nginx
COPY nginx.conf /etc/nginx/conf.d/

# Copia i file del frontend
COPY *.html /usr/share/nginx/html/

# Espone la porta
EXPOSE 80

# Comando di avvio
CMD ["nginx", "-g", "daemon off;"]